<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>XXX.TestBench.Devices</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../XXX.TestBench.Core/XXX.TestBench.Core.csproj" />
  </ItemGroup>
</Project>
