<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>XXX.TestBench.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="FreeSql" Version="3.5.213" />
    <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.5.213" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../XXX.TestBench.Core/XXX.TestBench.Core.csproj" />
  </ItemGroup>
</Project>
