<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>XXX.TestBench.Gateway.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../XXX.TestBench.Gateway/XXX.TestBench.Gateway.csproj" />
    <None Include="../../config/gatewaysettings.json" Link="config/gatewaysettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
